3<section class="h-screen flex justify-center items-center">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0" style="width: 500px;">
        <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
            My Snippet 🧑‍💻
        </a>
        <div class="w-full bg-white dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                    Halaman Login
                </h1>
                <form class="space-y-4 md:space-y-6" action="/login" method="post" id="form-login">
                    <small id="message-login-error" class="text-red-700 hidden"></small>
                    <div>
                        <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                        <input type="email" name="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="fulan@gmail.com">
                    </div>
                    <div>
                        <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                        <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    </div>
                    <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" id="btn-login">Login</button>
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        Belum punya akun? <a href="/register" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Daftar</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>

<script>
    document.getElementById("btn-login").addEventListener("click", async function(e) {
        e.preventDefault();

        try {
            const response = await fetch("/login", {
                method: "POST",
                body: new FormData(document.getElementById("form-login"))
            })

            const {
                meta,
                data
            } = await response.json()

            if (meta.status != "success") {
                document.getElementById("message-login-error").classList.remove("hidden")
                document.getElementById("message-login-error").textContent = meta.message
                document.getElementById("form-login").reset()
                return
            }

            document.location.href = "/";
        } catch (error) {
            console.error(error.message)
        }
    })
</script>