<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="<?= BASE_URL . "assets/custom/style.css" ?>">
    <link rel="stylesheet" href="<?= BASE_URL . "assets/third-party/prismjs/prism-dracula.css" ?>">
</head>

<body>