<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Snippet 🧑‍💻 | <?= $data['title'] ?? '' ?></title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link href="https://cdn.jsdelivr.net/npm/@ryusei/light@1.2.0/dist/css/themes/ryuseilight-ginga.min.css" rel="stylesheet">
</head>

<body>

    <?php if ($data['title'] != "Login" && $data['title'] != "Register") : ?>
        <nav class="bg-white border-gray-200 dark:bg-gray-900 py-3">
            <div class="flex flex-wrap justify-between items-center container mx-auto p-4">
                <a href="/" class="flex items-center">
                    <span class="text-4xl">🧑‍💻</span>
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">My Snippet</span>
                </a>
                <div class="flex items-center">
                    <span class="mr-6 text-sm  text-gray-500 dark:text-white hover:underline"><?= $data['user']->fullname ?></span>
                    <a href="/logout" class="text-sm  text-blue-600 dark:text-blue-500 hover:underline">Logout</a>
                </div>
            </div>
        </nav>
    <?php endif; ?>